version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
  
  app:
    image: your-app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db